// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCst4LrDhPnVxkgwBXW1nVpbqfChcgc4bE',
    appId: '1:512411420211:web:e74d00e3c467302dfa8546',
    messagingSenderId: '512411420211',
    projectId: 'rbuy-b88dd',
    authDomain: 'rbuy-b88dd.firebaseapp.com',
    storageBucket: 'rbuy-b88dd.appspot.com',
    measurementId: 'G-6X6XZX0NHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhzqHE94OmOe62MRJrCKzFFioM-jCbdH8',
    appId: '1:512411420211:android:0b172f6e7731daccfa8546',
    messagingSenderId: '512411420211',
    projectId: 'rbuy-b88dd',
    storageBucket: 'rbuy-b88dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDx6XTf-Tu6EjZzUU3Wd0vjyJ-Q4sTwB4',
    appId: '1:512411420211:ios:80b81301c28557d2fa8546',
    messagingSenderId: '512411420211',
    projectId: 'rbuy-b88dd',
    storageBucket: 'rbuy-b88dd.appspot.com',
    iosBundleId: 'com.example.rbuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDx6XTf-Tu6EjZzUU3Wd0vjyJ-Q4sTwB4',
    appId: '1:512411420211:ios:80b81301c28557d2fa8546',
    messagingSenderId: '512411420211',
    projectId: 'rbuy-b88dd',
    storageBucket: 'rbuy-b88dd.appspot.com',
    iosBundleId: 'com.example.rbuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCst4LrDhPnVxkgwBXW1nVpbqfChcgc4bE',
    appId: '1:512411420211:web:f928cd4ac6e97af6fa8546',
    messagingSenderId: '512411420211',
    projectId: 'rbuy-b88dd',
    authDomain: 'rbuy-b88dd.firebaseapp.com',
    storageBucket: 'rbuy-b88dd.appspot.com',
    measurementId: 'G-VB44TLLS5Z',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCst4LrDhPnVxkgwBXW1nVpbqfChcgc4bE',
    appId: '1:512411420211:web:e74d00e3c467302dfa8546',
    messagingSenderId: '512411420211',
    projectId: 'rbuy-b88dd',
    authDomain: 'rbuy-b88dd.firebaseapp.com',
    storageBucket: 'rbuy-b88dd.appspot.com',
    measurementId: 'G-6X6XZX0NHF',
  );
}
